# MaƸlumat


## Arab caliphs and the Shi'a split

From: Hitti, *History of the Arabs*

The first four caliphs were known as the "orthodox caliphs". They held sway from Medina.

- Abu Bakr (r. 632-634)

- 'Umar (r. 634-644)
  - appointed a six-member board of electors to decide on next caliph; stated that his son was not to be his successor
  - this shoed that the old Arabian idea of the tribal chief had triumphed over the idea of the hereditary ruler

- 'Uthman (r. 644-656)
  - there was a protest against 'Uthman and he was killed
  - 'Aishah, Muhammad's favourite wife, had been involved in it in some way

- 'Ali (r. 656-661)
  - 'Ali was Muhammad's first cousin and husband of Muhammad's favourite daughter, Fatimah; they had two sons, Hasan and Husayn
  - the party he represented had long maintained 'Ali was the legitimate successor to Muhammad!
  - almost the whole Muslim world accepted his succession as caliph
  - some were opposed to him - 'Aishah, now "the mother of the believers", joined up with these opponents in Basra; she hated him because of an earlier personal dispute between them where he'd questioned her integrity
  - the two sides confronted each other at Basra; the "battle of the camel" (named from 'Aisha's mount) ensued; 'Ali won; 'Aisha, still treated as "first lady", was sent back to Medina
  - 'Ali moved his capital to Kufa not long after he became caliph

This was the first "civil war".

Mu'awiyah, governor of Syria and relative of 'Uthman, emerged to avenge the killing of 'Uthman.
  
Mu'awiyah refused to accept 'Ali as caliph and challenged 'Ali to produce 'Uthman's killer, saying that, if he didn't produce the killer, he'd be an accomplice to the murder and ineligible to be caliph.

This also raised the question about whether Iraq or Syria would dominate Islamic affairs.

The two sides faced off near Raqqa (in present day northern Syria) in 657. There was a very drawn-out arbitration process, the details of which are unclear. In this process, which ended in 659, 'Ali lost status and Mu'wiyah gained some.

After 'Ali was killed in 661, Mu'awiyah became caliph, having been the caliph in waiting (but already accepted by some) since 659. He'd actually been proclaimed caliph in Jerusalem in 660. 'Ali was buried at al-Najaf, now a major Muslim pilgrimmage centre.

Mu'awiyah (r. 661-680) established Damascus as the capital of the Muslim empire. He nominated his son, Yazid, as his successor. This introduced the hereditary principle into the caliphate.

Mu'awiyah was the first of the Umayyad caliphs (661-750).

The Iraqis refused to accept Mu'awiyah as caliph and put up Hasan, 'Ali and Fatimah's elder son, as 'Ali's true successor. Hasan wasn't particularly interested and was bought off by Mu'awiyah.

When Yazid succeeded his father, Mu'awiyah in 680, Iraqis pushed Husayn to challenge Yazid.

On 10th Muharram, 680, Husayn and a group of a couple of hundred relatives and followers were confronted by forces loyal to Yazid. Husayn's group refused to surrender and were all killed.

Shi'ism was born on 10th Muharram, as a result of Husayn's death.

Shi'ites hold strongly to the idea of the imamship. The first imam for shi'ites was 'Ali.

The majority of Shi'ites hold that there has been a succession of twelve imams descended from 'Ali, who was the first of these twelve. His sons Hasan and Husayn were the second and third, respectively, in this line. Those who hold this belief are the "Twelvers".

One group of Shi'ites holds that there have only been seven visible imams, the last of whom was Isma'il. They hold that the rightful seventh imam was Isma'il and not his brother, Musa, who the Twelvers put in seventh place. This sect of Shi'ites is the Isma'ilites.

Shi'ites were largely made up of people who reveloted against the established Islamic order. Consequently, many Shi'ite sects have developed.

## Alawites

One group of non-Muslim people were attracted to Muhammad ibn Nusayr, who was a follower of the eleventh imam (in the sequence of twelve). This group, which was pagan, converted to Islam. They are considered an Isma'ili sect (why, if the Isma'ilis stopped at seven imams?!) and are known as Nusayris. They kept some of their pagan beliefs and took on some Christian festivals (Christmas and Easter). They have lived mainly around northern and central Syria and were mostly peasants.

When the French got the mandate for Syria after World War 1, the Nusayris, who lived in north-west Syria around Latakia, became officially known as the Alawites (علوي).


## Sunnis and Shi'ites

The sunna (السُنّة) are the actions and sayings of Muhammad. They are recorded as the hadith (حَديث).

The hadith were made legally binding, in addition to the law laid down in the Quran. The Quran and the hadith make up the two most important sources of religious doctrine.

The Sunnis (orthodox Muslims) hold to the succession of the caliphs through 'Ali to Mu'awiyah and on through the Ummayads, Abbasids etc.

The Shi'ites hold that the imam is more important than the caliph. They believe that 'Ali is Muhammad's rightful successor (i.e. 'Ali should've been the first caliph). While the Sunnis hold that the Quran is the intermediary between God and humanskind, the Shi'ites hold that the imam is that intermediary (Hitti, p. 247).

The name, Shi'a, comes from the word for "follower". The followers of 'Ali are the Shi'a (الشيعة).



